### ISSUE TITLE
Inputs do not work within describe.one do blocks in version 4.17.7

### ISSUE THREAD

**Issue by Sean89us** [inspec/inspec#4523]
# Describe the problem
In version 4.17.7 of inspec, inputs do not work with a describe.one block. Example:
```
control 'V-13729' do
  title 'The httpd.conf MaxSpareServers directive must be set properly. '
  apache_conf_file_path = input('apache_conf_file_path', value: '/etc/httpd/conf/httpd.conf', description: 'Location of the configuration file of the Apache service')

  describe.one do
    describe apache_conf(apache_conf_file_path) do
      its('MaxSpareServers') { should cmp <= 10 }
    end
    describe apache_conf(apache_conf_file_path) do
      its('MaxSpareServers') { should cmp == nil }
    end
  end
end
```
results in
```
  ×  V-13729: The httpd.conf MaxSpareServers directive must be set properly.
     ×  Control Source Code Error cerner_Apache_2.2_STIG_inspec/cerner_Apache_2.2_Server_STIG_inspec/controls/V-13729.rb:1
     undefined local variable or method `apache_conf_file_path' for #<#<Class:0x00007f8b02ca7a30>:0x00007f8b01ca4d40>

```

Whereas in version 4.16.0 I can run the same control and it gets this result:
```
 ✔  V-13729: The httpd.conf MaxSpareServers directive must be set properly.
     ✔  Apache Config /etc/httpd/conf/httpd.conf MaxSpareServers should cmp == nil
```

**Comment by clintoncwolfe** [comment]
Funny, I didn't think this worked yet - #3650

**Comment by kekaichinose** [comment]
Per the community, this worked in 4.16.x release so a regression introduced in 4.17.x

**Comment by clintoncwolfe** [comment]
I am unable to reproduce the issue using the reproduction code given by the OP, but this code here does indeed break in 4.17.7+ (approximately):
```
control "control-01" do
  value = input("input-inner-control", value: "test-value-01") # Works

  describe.one do
    value = input("input-outer-test", value: "test-value-02") # Breaks
    describe "test-value-03" do
      it { should cmp input("input-inner-test", value: "test-value-03") }  # Unclear
    end
  end
end

```
(note that the `input` call is moved to inside the describe.one)

Failure is 
```
  ×  control-01: describe-one/controls/describe-one.rb:1
     ×  Control Source Code Error describe-one/controls/describe-one.rb:1
     undefined method `input' for #<#<Class:0x00007fa219e233e0>:0x00007fa219e23228>
```
Mind you, AFAIK #3650 really is true; I don't think we ever had attribute/input support in describe.one blocks - I don't see any evidence of that in the codebase. This looks superficially related to #4365, but I don't think it is.
