### ISSUE TITLE
mysql_session fails with undefined method `stdout' 

### ISSUE THREAD

**Issue by ramereth** [inspec/inspec#5218]
I've confirmed that #5124 introduced the following bug:

```
  ×  mariadb_database: test creation and removal of databases (2 failed)
     ×  MySQL query: show databases stdout 
```

You can also see it in action [here](https://github.com/sous-chefs/mariadb/pull/313/checks?check_run_id=1010399944).

If I roll back to version 4.22.1 this problem goes away, but when I update to 4.22.2 and beyond, this issue is happening.

**Comment by daks** [comment]
I have been affected by the same bug, and for me too rolling back to 4.22.1 solves it.

**Comment by Schwad** [comment]
Thanks for the catch folks, and the help with the PR! I have merged it and it will be available in the next InSpec release (which fingers crossed is this week!)
