### ISSUE TITLE
inspec breaks custom resources after 4.18.83

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4925]
# Describe the problem

The library eval context work on #4814 (included on 4.18.85 and 4.18.95) introduced a regression breaking the inspec-aws resource pack (EDIT: any resource pack that defines custom resources by calling `Inspec.resource(1)` in the `libraries/` folder). 

One workaround is to use version 4.18.51.

## Repro:

A minimal AWS profile (use `inspec init profile -p aws myprofile`) will break:
`inspec exec myprofile -t aws://fakecreds` 

You don't need to actually setup AWS creds to trigger the error.

Stacktrace:
```
NoMethodError: undefined method `resource' for :nope!:Symbol
Did you mean?  rescue
  libraries/aws_backend.rb:154:in `block in initialize'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/dsl_shared.rb:47:in `eval'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/dsl_shared.rb:47:in `require'
  libraries/aws_alb.rb:3:in `load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:170:in `instance_eval'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:170:in `load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:159:in `load_library_file'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:144:in `block in load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:143:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:143:in `load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:272:in `load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:265:in `block in load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:247:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:247:in `each_with_index'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:247:in `load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:107:in `block in load'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:101:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:101:in `load'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:129:in `run'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/cli.rb:289:in `exec'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/base_cli.rb:35:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-incident/inspec-bin/bin/inspec:11:in `<top (required)>'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/inspec:23:in `load'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/inspec:23:in `<top (required)>'
```

Related - https://github.com/newcontext-oss/kitchen-terraform/issues/384

**Comment by skpaterson** [comment]
Thanks for raising this @clintoncwolfe - looks like the same applies to Azure and there is another related error with GCP for InSpec v4.18.85:

``` 
$ bundle exec inspec exec aztest -t azure://
bundler: failed to load command: inspec (/Users/spaterson/Documents/workspace/azure/older-inspec-test/vendor/ruby/2.7.0/bin/inspec)
NoMethodError: undefined method `resource' for :nope!:Symbol
Did you mean?  rescue
  libraries/azurerm_resource.rb:6:in `block in initialize'
  /Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/dsl_shared.rb:47:in `eval'
  /Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/dsl_shared.rb:47:in `require'
  libraries/azurerm_ad_user.rb:3:in `load_with_context'
...
 ```

For the GCP resource pack there is a new different error:

``` 
... <lots of output curtailed>
ibe google_users(customer: 'my_customer') do\n        it { should exist }\n      end\n    \"\n\n    def initialize(opts = {})\n      # Call the parent class constructor\n      super(opts)\n      @customer = opts[:customer] || 'my_customer'\n      @domain = opts[:domain] || ''\n    end\n\n    # FilterTable setup\n    filter_table_config = FilterTable.create\n    filter_table_config.add(:user_ids, field: :user_id)\n    filter_table_config.add(:user_full_names, field: :user_full_name)\n    filter_table_config.add(:user_emails, field: :user_email)\n    filter_table_config.connect(self, :fetch_data)\n\n    def fetch_data\n      user_rows = []\n      next_page = nil\n      loop do\n        catch_gcp_errors do\n          @users = @gcp.gcp_admin_client.list_users(customer: @customer, domain: @domain, page_token: next_page)\n        end\n        return [] if !@users || !@users.users\n        @users.users.map do |user|\n          user_rows+=[{ user_id: user.id,\n                        user_name: user.name.full_name,\n                        user_email: user.primary_email }]\n        end\n        next_page = @users.next_page_token\n        break unless next_page\n      end\n      @table = user_rows\n    end\n  end\nend\n", ref="libraries/google_users.rb", line=nil, loaded=false>}>, @__inspec_binding=#<Binding:0x00007fbe2fb60fb8>, @res_klass=#<Class:0x00007fbe2fb60f18>> is not a class/module
libraries/google_compute_address.rb:5:in `load_with_context'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:170:in `instance_eval'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:170:in `load_with_context'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:159:in `load_library_file'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:144:in `block in load_libraries'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:143:in `each'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile_context.rb:143:in `load_libraries'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:272:in `load_libraries'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:265:in `block in load_libraries'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `each'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `each_with_index'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/profile.rb:247:in `load_libraries'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:107:in `block in load'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:101:in `each'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:101:in `load'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/runner.rb:129:in `run'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/cli.rb:289:in `exec'
/Users/spaterson/vendor/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/spaterson/vendor/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/spaterson/vendor/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/Users/spaterson/vendor/ruby/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-core-4.18.85/lib/inspec/base_cli.rb:35:in `start'
/Users/spaterson/vendor/ruby/2.7.0/gems/inspec-bin-4.18.85/bin/inspec:11:in `<top (required)>'
/Users/spaterson/vendor/ruby/2.7.0/bin/inspec:23:in `load'
/Users/spaterson/vendor/ruby/2.7.0/bin/inspec:23:in `<top (required)>' 
```

**Comment by clintoncwolfe** [comment]
Looks like anything that calls `Inspec.resource(1)` in the libraries will fail (which should be an OK thing to do).

For GCP, I get a 755kB stacktrace full of autogenerated code using a profile generated using inspec init. The issue appears on 4.18.83. I'm not digging into that yet, until we have the general issue resolved; if there is more specific to GCP I'll cut a new issue.

**Comment by ehaselwanter** [comment]
this breaks chef-workstation too:

with 

```bash
chef -v
Chef Workstation version: 0.16.31
Chef Infra Client version: 15.8.23
Chef InSpec version: 4.18.85
Chef CLI version: 2.0.0
Test Kitchen version: 2.3.4
Cookstyle version: 5.21.9
```

I get:

```bash
E, [2020-02-29T09:52:07.265756 #43906] ERROR -- default-azure: Message: Verifying the 'azure' system failed:
        Running InSpec failed:
        undefined method `resource' for :nope!:Symbol
Did you mean?  rescue
```
