### PR TITLE
Fix mysql_session stdout, stderr and exit_status parameters

### LINKED ISSUE #5218: mysql_session fails with undefined method `stdout'
I've confirmed that #5124 introduced the following bug:

```
  ×  mariadb_database: test creation and removal of databases (2 failed)
     ×  MySQL query: show databases stdout 
```

You can also see it in action [here](https://github.com/sous-chefs/mariadb/pull/313/checks?check_run_id=1010399944).

If I roll back to version 4.22.1 this problem goes away, but when I update to 4.22.2 and beyond, this issue is happening.

### PR DESCRIPTION
**Pull request by ramereth**
A feature introduced in #5124 changed how the mysql_session resource works to
where stdout, stderr, and exit_status no longer worked. The Lines class only
exposes output instead of stdout, stderr and exit_status.

As a work around, this adds backwards compatibilty for stdout, stderr and
exit_status parameters. In addition I updated the documentation to prefer output
over stdout/stderr.

This fixes #5218.

Signed-off-by: Lance Albertson <lance@osuosl.org>

## Description

I wasn't sure if we wanted to deprecate ``stdout``and ``stderr`` or not so please let me know if we do.

## Related Issue
- #5218 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by fzipi** [comment]
Good catch!

**Review by rmoles — APPROVED** [review]
This seems like a reasonable change to make. Bonus for updating the documentation to prefer output.

**Review by Schwad — APPROVED** [review]
Thank you so much for this @ramereth - great catch! We'll get this going and in the next release to revert the issue
