### PR TITLE
   Fix broken unit test by adding require

### LINKED ISSUE #4468: Tests broken by a phase 2 waivers commit
My local checkout is broken for 2 files. This issue focuses on `test/unit/profiles/control_eval_context_test.rb`.

Here's my output from magit's bisect:

```
6ec50efd229d34e5b0b2102c96d69cb354210c1c is the first bad commit
commit 6ec50efd229d34e5b0b2102c96d69cb354210c1c
Author: Clinton Wolfe <clintoncwolfe@gmail.com>
Date:   Wed Aug 28 20:42:10 2019 -0400
    Initial implementation of skipping a control by waivering it via input flagging
    
    Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>
 lib/inspec/rule.rb | 45 +++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 45 insertions(+)

Bisect Rest (1)
6ec50efd2 * bad Initial implementation of skipping a control by waivering it via input flagging

Bisect Log (8)
git bisect start 'master' 'zenspider/activated_eh'
e0e61155d bad Bump version to 4.16.10 by Chef Expeditor
4e822f3c3 good Refactored V2::Activator into more idiomatic ruby.

git bisect bad 43bc7e034387eccaff1b889c02dc7c57aae33909
43bc7e034 bad Modify @__skip_rule to distinguish only_if and waiver, and force waiver to win

git bisect good d96b0a32818114e5044ed534c5d16850aa09097d
d96b0a328 good Merge pull request #4446 from inspec/zenspider/activated_eh

git bisect good 6b618b6b83767cf18f9e42899b9cd4ca2bd10412
6b618b6b8 good Comments for clarity on skipping

git bisect bad ff209b4bae5214d7f9559d48b83324cbed58a46a
ff209b4ba bad Refactor control_id lookup in waiver test file

git bisect bad 6ec50efd229d34e5b0b2102c96d69cb354210c1c
6ec50efd2 bad Initial implementation of skipping a control by waivering it via input flagging

git bisect good eb1ec437d7917edeacc0c1dd372628518abece8a
eb1ec437d good Linting and test number corrections

6ec50efd229d34e5b0b2102c96d69cb354210c1c is the first bad commit
```

### Full Run output:

Note in the output that it seems like there are 2 different errors. The error on master is different than the error of the first bad commit in the bisect.

```
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 38132

# Running:

...E

Finished in 0.022407s, 178.5156 runs/s, 178.5156 assertions/s.

  1) Error:
Inspec::ControlEvalContext#test_0002_provides rules with access to the given DSL:
NoMethodError: undefined method `its' for RSpec::ExampleGroups::ControlSourceCodeError:Class
Did you mean?  it
    /Users/ryan/.gem/repos/inspec/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:738:in `method_missing'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:70:in `block in initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:343:in `instance_exec'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:343:in `block in with_dsl'
    /Users/ryan/.gem/repos/inspec/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:387:in `module_exec'
    /Users/ryan/.gem/repos/inspec/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:387:in `subclass'
    /Users/ryan/.gem/repos/inspec/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:52:in `block (4 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:48:in `each'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:48:in `block (3 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:45:in `each'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:45:in `block (2 levels) in <top (required)>'

4 runs, 4 assertions, 0 failures, 1 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 43368

# Running:

....

Finished in 0.024820s, 161.1604 runs/s, 161.1604 assertions/s.

4 runs, 4 assertions, 0 failures, 0 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 51613

# Running:

....

Finished in 0.025013s, 159.9168 runs/s, 159.9168 assertions/s.

4 runs, 4 assertions, 0 failures, 0 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 22679

# Running:

...E

Finished in 0.003930s, 1017.8117 runs/s, 1017.8117 assertions/s.

  1) Error:
Inspec::ControlEvalContext#test_0002_provides rules with access to the given DSL:
NoMethodError: undefined method `instance' for Inspec::InputRegistry:Class
Did you mean?  instance_of?
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:285:in `__apply_waivers'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:54:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `block (2 levels) in create'
    (eval):1:in `block (2 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:44:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:44:in `block (2 levels) in <top (required)>'

4 runs, 4 assertions, 0 failures, 1 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 62035

# Running:

.E..

Finished in 0.003482s, 1148.7650 runs/s, 1148.7650 assertions/s.

  1) Error:
Inspec::ControlEvalContext#test_0002_provides rules with access to the given DSL:
NoMethodError: undefined method `instance' for Inspec::InputRegistry:Class
Did you mean?  instance_of?
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:285:in `__apply_waivers'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:54:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `block (2 levels) in create'
    (eval):1:in `block (2 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:44:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:44:in `block (2 levels) in <top (required)>'

4 runs, 4 assertions, 0 failures, 1 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 61211

# Running:

....

Finished in 0.024556s, 162.8930 runs/s, 162.8930 assertions/s.

4 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```

### PR DESCRIPTION
**Pull request by clintoncwolfe**
Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>

## Description

Repairs a sporadic broken unit test caused by a missing `require` statement, which was exacerbated by a swallowed exception.

In detail: because InputRegistry (which relies on Singleton) was not being required, when we called `Inspec::InputRegistry.instance` that would be an undefined class method. Due to random load order of tests and process sharing, the problem only struck occasionally; when it did, it may exhibit as a "Control source code error" because it was located in a catch-anything exception handling block.

Anyway, now we require it explicitly.

## Related Issue

Fixes #4468 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by miah — APPROVED** [review]

**Review by zenspider — APPROVED** [review]
Confirmed it works, but confused as to the source of the error given this fix.
