### PR TITLE
Ensure @params in shadow resource always has a valid value.

### LINKED ISSUE #2913: Breaking change in resource filters since 2.0.45
### 🎛 Description

We have profiles that we create and test with inspec 1.x; and now need to test and maintain for both inspec 1.x AND 2.x

### 🌍 InSpec and Platform Version

inspec-2.1.21 via `bundle install`

### 🤔 Replication Case

The following control works in Inspec 1.51 and Inspec 2.0.45 but fails in Inspec 2.1

```
control "Ensure inactive password lock is 30 days or less" do
  title "Ensure inactive password lock is 30 days or less"
  users = shadow.filter(password:/[^!|*]/).params.map { |x| x['user'] }
  unless users.empty?
    users.each do |user|
      describe shadow.users(user) do
        its('inactive_days') { should cmp <= 30 }
      end
    end
  else
    describe 'user password' do
      skip 'no user with password detected'
    end
  end
end
```

### 💁 Possible Solutions

Make the filter method backward compatible

### 💻 Stacktrace

```
root@510dc6aa1821:/workdir# cd /workdir && bundle exec inspec check my_profile
[DEPRECATION] The shadow `users` property is deprecated and will be removed in InSpec 3.0.  Please use `user` instead.
bundler: failed to load command: inspec (/workdir/vendor/bundle/ruby/2.5.0/bin/inspec)
NoMethodError: undefined method `find_all' for nil:NilClass
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/resources/shadow.rb:82:in `block in filter'
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/resources/shadow.rb:79:in `each'
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/resources/shadow.rb:79:in `filter'
  my_profile/controls/my-controls.rb:3:in `block in load_with_context'
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/inspec/rule.rb:50:in `instance_eval'
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/inspec/rule.rb:50:in `initialize'
```

### PR DESCRIPTION
**Pull request by miah**
Add tests for method chained shadow resource with readable and unreadable shadow files.

Ensure @params always has a safe value, otherwise we may stacktrace when
unable to read /etc/shadow and invoked with method chaining.

My only complaint with this is that when the `/etc/shadow` file is unreadable, you won't see the error when chaining; you'll need to test the file or a specific user.

image

Signed-off-by: Miah Johnson <miah@chia-pet.org>

Fixes #2913

### CODE REVIEW

**Review by jerryaldrichiii — APPROVED** [review]
Looks good to me! Thanks @miah!

File: lib/resources/shadow.rb [hunk 1]
```diff
@@ -43,7 +42,7 @@ def initialize(path = '/etc/shadow', opts = nil)
       @filters = opts[:filters] || ''
       @raw_content = opts[:content] || read_file_content(@path, allow_empty: true)
       @lines = @raw_content.to_s.split("\n")
-      @params = @lines.map { |l| parse_shadow_line(l) }
+      params
```
Comment (TrevorBramble) [inline lib/resources/shadow.rb]: I'd really rather see this assignment preserved, rather than treating the setup as a side-effect of calling a method.

```ruby
def initialize
  @params = set_params(@lines)
end

def set_params(lines)
  lines.nil? ? [] : lines.map { |l| parse_shadow_line(1) }
end
```

File: lib/resources/shadow.rb [hunk 2]
```diff
@@ -121,10 +120,14 @@ def to_s
       "/etc/shadow#{f}"
     end
 
+    def params
+      @params = @lines.nil? ? [] : @lines.map { |l| parse_shadow_line(l) }
+    end
```
Comment (TrevorBramble) [inline lib/resources/shadow.rb]: Couple of directions this could go to make the point more obvious.

You could separate the guard statement:
```ruby
def params(lines)
  return [] if lines.nil?

  lines.map { |l| parse_shadow_line(1) }
end
```
And that maps directly to your logic in the ternary. But what I think you're actually concerned about is calling `map` on `nil`? So this would actually be more direct and clear:
```ruby
def params(lines)
  Array(lines).map { |l| parse_shadow_line(1) }
end
```
`Array(nil)` will produce the empty array, and pass through the `map` call to return what you expect, just that empty array. So there's one path through the code and all the needed safety.

File: lib/resources/shadow.rb [hunk 3]
```diff
@@ -121,10 +120,14 @@ def to_s
...
+
     private
 
     def map_data(id)
-      @params.map { |x| x[id] }
+      params.map { |x| x[id] }
```
Comment (TrevorBramble) [inline lib/resources/shadow.rb]: Consider using `collect` here instead of `map` to make it clear that you're collecting a new set of values from the input data. (Same for the parsed shadow lines in the `params` method.)

File: test/unit/resources/shadow_test.rb [hunk 4]
```diff
@@ -86,6 +86,24 @@
     end
   end
 
+  describe 'when method chained' do
+    let(:unreadable_shadow) { load_resource('shadow', '/etc/unreadable_shadow') }
+    it 'can read /etc/shadow and #filter matches user with no password and inactive_days' do
```
Comment (TrevorBramble) [inline test/unit/resources/shadow_test.rb]: Separate sections with newlines please. =^)

File: lib/resources/shadow.rb (hunk 1 above)
Comment (TrevorBramble) [reply lib/resources/shadow.rb]: While we're there, `@raw_content` and `@lines` are only used in the initializer (if you pass `@lines` to the `params` method) so why not make them local variables instead? You could even inline the lines parsing because there's no conditional logic involved.
```
def initialize(path = '/etc/shadow', opts = nil)
  # ...
  params(raw_content.to_s.split("\n"))
end
```

...And while we're there
```ruby
def initialize(path = '/etc/shadow', opts = nil)
  opts ||= {}
  # ...
end
```
This makes me so sad. Would you mind?
```ruby
def initialize(path = '/etc/shadow', opts = {})
  # ...
end
```

**Review by TrevorBramble — CHANGES_REQUESTED** [review]
You asked for it! ;^)

File: lib/resources/shadow.rb (hunk 1 above)
Comment (miah) [reply lib/resources/shadow.rb]: I like this `@params = params(@raw_content.to_s.split("\n"))` but when I set up our params this way, when `filter` is called I'm still getting a nil value.

```
NoMethodError: undefined method `find_all' for nil:NilClass
  /Users/miah/projects/github/tmp/inspec/lib/resources/shadow.rb:80:in `block in filter'
```

So what I've done is preserved `@lines` and reference that from set_params.

Comment (TrevorBramble) [reply lib/resources/shadow.rb]: Ah, I missed `def lines` elsewhere. Still, I'd pass it into the new method that makes your params and use it as a local variable there.

File: lib/resources/shadow.rb [hunk 5]
```diff
@@ -35,15 +35,13 @@ class Shadow < Inspec.resource(1)
     include FileReader
 
     attr_reader :params
-    attr_reader :lines
 
-    def initialize(path = '/etc/shadow', opts = nil)
-      opts ||= {}
+    def initialize(path = '/etc/shadow', opts = {})
```
Comment (TrevorBramble) [inline lib/resources/shadow.rb:39]: Thank you!

**Review by TrevorBramble — APPROVED** [review]

File: lib/resources/shadow.rb [hunk 6]
```diff
@@ -35,15 +35,13 @@ class Shadow < Inspec.resource(1)
...
       @path = path || '/etc/shadow'
```
Comment (chris-rock) [inline lib/resources/shadow.rb]: I am wondering if we could check if the file exist and throw an exception here? Otherwise we absorb the error.

File: lib/resources/shadow.rb [hunk 7]
```diff
@@ -35,15 +35,13 @@ class Shadow < Inspec.resource(1)
...
       @filters = opts[:filters] || ''
-      @raw_content = opts[:content] || read_file_content(@path, allow_empty: true)
-      @lines = @raw_content.to_s.split("\n")
-      @params = @lines.map { |l| parse_shadow_line(l) }
+      raw_content = opts[:content] || read_file_content(@path, allow_empty: true)
```
Comment (chris-rock) [inline lib/resources/shadow.rb]: I think it would be beneficial to move the read logic out of the initialize function and do this during runtime not object creation time. This would allow us to do less during `inspec check` runs.

File: lib/resources/shadow.rb (hunk 6 above)
Comment (miah) [reply lib/resources/shadow.rb]: Definitely can do this, but the file resource we use for reading and content gathering also does this; but we do absorb the error when method chained.

**Review by TrevorBramble — APPROVED** [review]
<emoji>

**Review by jquick — APPROVED** [review]
Thanks @miah
