### PR TITLE
Add several Builders and Testers to Omnibus

### PR DESCRIPTION
**Pull request by snapp**
## Description
This PR updates the Builder/Tester mapping with the following additions:

### New Builders
* EL 7 (aarch64)
* Ubuntu 18.04 (aarch64)
* SLES 15 (aarch64)
* Debian 10 (aarch64)

### New Testers
* EL 7 (aarch64)
* EL 8 (aarch64)
* Amazon Linux 2 (x86_64)
* Amazon Linux 2 (aarch64)
* Ubuntu 18.04 (aarch64)
* Ubuntu 20.04 (aarch64)
* SLES 15 (aarch64)
* Debian 10 (aarch64)

An adhoc build is available here:

https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/125

Signed-off-by: Christopher A. Snapp csnapp@chef.io

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by snapp** [comment]
@clintoncwolfe, my original adhoc build for this PR (https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/124) blew up on SLES 15 aarch64 and Ubuntu 18.04 aarch64 with errors compiling `unf_ext`.

A bit of digging uncovered your PR from last year "Re-add a bespoke unf_ext to our omnibus build" #3902 followed a month later with @tas50's PR "Use the upstream unf_ext again" #3963.

I'm not sure I understand what was going on at the time that allowed the upstream `unf_ext` to work, but if I revert @tas50's commit I see successful builds again.

Should I leave that commit reverted?

**Comment by clintoncwolfe** [comment]
For a brief period in spring 2019, there was a needed fix to Solaris SPARC support in the unf_ext library. Over the course of time, we had it in a personal rep, then in a chef/ repo, then it was merged but not yet released in the upstream repo. #3902 was one moment in time when we were using the chef/ copy; and #3963 would be the moment of returning to "normalcy" after the upstream project had merged and released the fix.

In 0.0.7.6, there were changes related to compiler options on Solaris and AIX, and a gem update; and that's about it. There has not been a later release. I'm surprised that the `chef/` copy build OK on aarch64 when 0.0.7.6 didn't, I  don't have a good explanation for that. Could you link to a passing build?

If it works, I suppose we stay on it, but we should add a note explaining the relationship with aarch64.

**Comment by snapp** [comment]
Adhoc 124 failed with the compilation error on `unf_ext 0.0.7.2`.

Adhoc 125 linked in this PR's description succeeded when I simply reverted #3963

After your comment I wondered if I could just help bundler resolve a version of unf_ext newer than `0.0.7.2` so instead of reverting #3963 I just updated the Gemfile.  Adhoc 127 seems to show that this works, so maybe this is the appropriate fix?

**Comment by snapp** [comment]
@clintoncwolfe I've removed the WIP and this PR may be ready to merge depending on your thoughts regarding the `gem "unf_ext", "~> 0.0.7.6"` commit.

Here's a link to the adhoc showing it all working:

https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/127

**Review by clintoncwolfe — APPROVED** [review]
I think this will work - thanks!

**Comment by clintoncwolfe** [comment]
If you rebase against master, you should get passing tests; we added some test fixes for ruby 2.7.

**Comment by snapp** [comment]
@clintoncwolfe I've rebased my branch but I misunderstood your comment about the verify tests so I kicked off another adhoc:

https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/128

**Comment by Schwad** [comment]
I'll defer to @clintoncwolfe and @james-stocks on this one but looks relatively good to me, if they're happy with it so am I! 👍

**Comment by snapp** [comment]
@clintoncwolfe, verify step `run-tests-ruby-2.7` is still failing following the rebase.

**Comment by james-stocks** [comment]
The tests for this PR branch are resolving train to 3.1.8 : https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/1733#62051e19-9905-4562-a542-a552a71f66f7/417-652

Recent builds that passed resolved train to 3.2.28 : https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/1740#51e4c7ee-63ef-49dd-a5f1-3a7afd68af79/417-608

This older train will be missing @clintoncwolfe 's [work for Ruby 2.7 support](https://github.com/inspec/train/pull/5820, along with other newer commits that will be at least as valuable.

Since this PR branch is rebased against master, I would suspect that the change to `Gemfile` in this PR is causing the test failure.

**Comment by snapp** [comment]
This adhoc build shows that the latest rebase on master has everything building properly so I think it may be ready to merge:

https://buildkite.com/chef/inspec-inspec-master-omnibus-adhoc/builds/131

**Comment by james-stocks** [comment]
@christopher-snapp - this PR is causing train to resolve to an older version (3.1.8). That's causing the verify fail.

When I make your branch depend on at least train 3.2, bundler highlights this conflict:

```
Bundler could not find compatible versions for gem "unf_ext":
  In Gemfile:
    unf_ext (~> 0.0.7.6)

    inspec was resolved to 4.18.113, which depends on
      train (~> 3.2) was resolved to 3.2.5, which depends on
        azure_mgmt_resources (~> 0.15) was resolved to 0.17.4, which depends on
          ms_rest_azure (~> 0.11.0) was resolved to 0.11.2, which depends on
            unf_ext (= 0.0.7.2)
```

Moving to a newer unf_ext may not be trivial :(

**Review by james-stocks — CHANGES_REQUESTED** [review]
"Requesting changes" just to be clear that this can't merge until we solve the gem dependencies

**Comment by snapp** [comment]
@james-stocks Totally understand and I'm sorry for the noise.  I had forgotten that the issue was the verify pipeline when I stumbled back on this PR that was still open and reran an adhoc without stopping to get my head back on it.

I'll take a closer look

**Review by james-stocks — APPROVED** [review]
Thanks very much @christopher-snapp
