### ISSUE TITLE
Tests broken by a phase 2 waivers commit

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4468]
My local checkout is broken for 2 files. This issue focuses on `test/unit/profiles/control_eval_context_test.rb`.

Here's my output from magit's bisect:

```
6ec50efd229d34e5b0b2102c96d69cb354210c1c is the first bad commit
commit 6ec50efd229d34e5b0b2102c96d69cb354210c1c
Author: Clinton Wolfe <clintoncwolfe@gmail.com>
Date:   Wed Aug 28 20:42:10 2019 -0400
    Initial implementation of skipping a control by waivering it via input flagging
    
    Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>
 lib/inspec/rule.rb | 45 +++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 45 insertions(+)

Bisect Rest (1)
6ec50efd2 * bad Initial implementation of skipping a control by waivering it via input flagging

Bisect Log (8)
git bisect start 'master' 'zenspider/activated_eh'
e0e61155d bad Bump version to 4.16.10 by Chef Expeditor
4e822f3c3 good Refactored V2::Activator into more idiomatic ruby.

git bisect bad 43bc7e034387eccaff1b889c02dc7c57aae33909
43bc7e034 bad Modify @__skip_rule to distinguish only_if and waiver, and force waiver to win

git bisect good d96b0a32818114e5044ed534c5d16850aa09097d
d96b0a328 good Merge pull request #4446 from inspec/zenspider/activated_eh

git bisect good 6b618b6b83767cf18f9e42899b9cd4ca2bd10412
6b618b6b8 good Comments for clarity on skipping

git bisect bad ff209b4bae5214d7f9559d48b83324cbed58a46a
ff209b4ba bad Refactor control_id lookup in waiver test file

git bisect bad 6ec50efd229d34e5b0b2102c96d69cb354210c1c
6ec50efd2 bad Initial implementation of skipping a control by waivering it via input flagging

git bisect good eb1ec437d7917edeacc0c1dd372628518abece8a
eb1ec437d good Linting and test number corrections

6ec50efd229d34e5b0b2102c96d69cb354210c1c is the first bad commit
```

### Full Run output:

Note in the output that it seems like there are 2 different errors. The error on master is different than the error of the first bad commit in the bisect.

```
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 38132

# Running:

...E

Finished in 0.022407s, 178.5156 runs/s, 178.5156 assertions/s.

  1) Error:
Inspec::ControlEvalContext#test_0002_provides rules with access to the given DSL:
NoMethodError: undefined method `its' for RSpec::ExampleGroups::ControlSourceCodeError:Class
Did you mean?  it
    /Users/ryan/.gem/repos/inspec/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:738:in `method_missing'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:70:in `block in initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:343:in `instance_exec'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:343:in `block in with_dsl'
    /Users/ryan/.gem/repos/inspec/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:387:in `module_exec'
    /Users/ryan/.gem/repos/inspec/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:387:in `subclass'
    /Users/ryan/.gem/repos/inspec/gems/rspec-core-3.8.2/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:52:in `block (4 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:48:in `each'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:48:in `block (3 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:45:in `each'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:45:in `block (2 levels) in <top (required)>'

4 runs, 4 assertions, 0 failures, 1 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 43368

# Running:

....

Finished in 0.024820s, 161.1604 runs/s, 161.1604 assertions/s.

4 runs, 4 assertions, 0 failures, 0 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 51613

# Running:

....

Finished in 0.025013s, 159.9168 runs/s, 159.9168 assertions/s.

4 runs, 4 assertions, 0 failures, 0 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 22679

# Running:

...E

Finished in 0.003930s, 1017.8117 runs/s, 1017.8117 assertions/s.

  1) Error:
Inspec::ControlEvalContext#test_0002_provides rules with access to the given DSL:
NoMethodError: undefined method `instance' for Inspec::InputRegistry:Class
Did you mean?  instance_of?
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:285:in `__apply_waivers'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:54:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `block (2 levels) in create'
    (eval):1:in `block (2 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:44:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:44:in `block (2 levels) in <top (required)>'

4 runs, 4 assertions, 0 failures, 1 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 62035

# Running:

.E..

Finished in 0.003482s, 1148.7650 runs/s, 1148.7650 assertions/s.

  1) Error:
Inspec::ControlEvalContext#test_0002_provides rules with access to the given DSL:
NoMethodError: undefined method `instance' for Inspec::InputRegistry:Class
Did you mean?  instance_of?
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:285:in `__apply_waivers'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:54:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `block (2 levels) in create'
    (eval):1:in `block (2 levels) in <top (required)>'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:44:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/control_eval_context_test.rb:44:in `block (2 levels) in <top (required)>'

4 runs, 4 assertions, 0 failures, 1 errors, 0 skips
511 % minitest test/unit/profiles/control_eval_context_test.rb
Run options: --seed 61211

# Running:

....

Finished in 0.024556s, 162.8930 runs/s, 162.8930 assertions/s.

4 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by zenspider** [comment]
OK. For the other file, I think it is the same commit:

### Magit Output:

```
6ec50efd229d34e5b0b2102c96d69cb354210c1c is the first bad commit
commit 6ec50efd229d34e5b0b2102c96d69cb354210c1c
Author: Clinton Wolfe <clintoncwolfe@gmail.com>
Date:   Wed Aug 28 20:42:10 2019 -0400
    Initial implementation of skipping a control by waivering it via input flagging
    
    Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>
 lib/inspec/rule.rb | 45 +++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 45 insertions(+)

Bisect Rest (1)
6ec50efd2 * bad Initial implementation of skipping a control by waivering it via input flagging

Bisect Log:
git bisect start 'master' 'zenspider/activated_eh'
e0e61155d bad Bump version to 4.16.10 by Chef Expeditor
4e822f3c3 good Refactored V2::Activator into more idiomatic ruby.

git bisect bad 43bc7e034387eccaff1b889c02dc7c57aae33909
43bc7e034 bad Modify @__skip_rule to distinguish only_if and waiver, and force waiver to win

git bisect good d96b0a32818114e5044ed534c5d16850aa09097d
d96b0a328 good Merge pull request #4446 from inspec/zenspider/activated_eh

git bisect good 6b618b6b83767cf18f9e42899b9cd4ca2bd10412
6b618b6b8 good Comments for clarity on skipping

git bisect bad ff209b4bae5214d7f9559d48b83324cbed58a46a
ff209b4ba bad Refactor control_id lookup in waiver test file

git bisect bad 6ec50efd229d34e5b0b2102c96d69cb354210c1c
6ec50efd2 bad Initial implementation of skipping a control by waivering it via input flagging

git bisect good eb1ec437d7917edeacc0c1dd372628518abece8a
eb1ec437d good Linting and test number corrections

git bisect good eb1ec437d7917edeacc0c1dd372628518abece8a
# first bad commit: [6ec50efd229d34e5b0b2102c96d69cb354210c1c] Initial implementation of skipping a control by waivering it via input flagging
# good: [eb1ec437d7917edeacc0c1dd372628518abece8a] Linting and test number corrections
# first bad commit: [6ec50efd229d34e5b0b2102c96d69cb354210c1c] Initial implementation of skipping a control by waivering it via input flagging
```


### Full Run Output:

```
517 % m test/unit/profiles/profile_context_test.rb:18 && minitest test/unit/profiles/profile_context_test.rb
Run options: -n "/^(test_0002_loads\\ an\\ empty\\ describe\\.one\\ block|test_0002_loads\\ an\\ empty\\ describe\\.one\\ block)$/" --seed 23321

# Running:

FF

Finished in 0.201742s, 9.9137 runs/s, 9.9137 assertions/s.

  1) Failure:
Inspec::ProfileContext::rule DSL#test_0002_loads an empty describe.one block [/Users/ryan/Work/git/inspec/inspec/test/unit/profiles/profile_context_test.rb:18]:
--- expected
+++ actual
@@ -1 +1 @@
-[["describe.one", [], nil]]
+[["describe.one", [], nil], ["describe", ["Control Source Code Error"], #<Proc:0xXXXXXX@/Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:341>]]


  2) Failure:
Inspec::ProfileContext::its default DSL#test_0002_loads an empty describe.one block [/Users/ryan/Work/git/inspec/inspec/test/unit/profiles/profile_context_test.rb:18]:
--- expected
+++ actual
@@ -1 +1 @@
-[["describe.one", [], nil]]
+[["describe", ["Control Source Code Error"], #<Proc:0xXXXXXX@/Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:341>], ["describe.one", [], nil]]


2 runs, 2 assertions, 2 failures, 0 errors, 0 skips
517 % m test/unit/profiles/profile_context_test.rb:18 && minitest test/unit/profiles/profile_context_test.rb
Run options: -n "/^(test_0002_loads\\ an\\ empty\\ describe\\.one\\ block|test_0002_loads\\ an\\ empty\\ describe\\.one\\ block)$/" --seed 35289

# Running:

..

Finished in 0.255030s, 7.8422 runs/s, 7.8422 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
Run options: --seed 55108

# Running:

.........................................................

Finished in 6.314906s, 9.0263 runs/s, 19.7944 assertions/s.

57 runs, 125 assertions, 0 failures, 0 errors, 0 skips
517 % m test/unit/profiles/profile_context_test.rb:18 && minitest test/unit/profiles/profile_context_test.rb
Run options: -n "/^(test_0002_loads\\ an\\ empty\\ describe\\.one\\ block|test_0002_loads\\ an\\ empty\\ describe\\.one\\ block)$/" --seed 14092

# Running:

..

Finished in 0.228122s, 8.7672 runs/s, 8.7672 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
Run options: --seed 1438

# Running:

.........................................................

Finished in 6.340609s, 8.9897 runs/s, 19.7142 assertions/s.

57 runs, 125 assertions, 0 failures, 0 errors, 0 skips
517 % m test/unit/profiles/profile_context_test.rb:18 && minitest test/unit/profiles/profile_context_test.rb
Run options: -n "/^(test_0002_loads\\ an\\ empty\\ describe\\.one\\ block|test_0002_loads\\ an\\ empty\\ describe\\.one\\ block)$/" --seed 61489

# Running:

EE

Finished in 0.216545s, 9.2360 runs/s, 0.0000 assertions/s.

  1) Error:
Inspec::ProfileContext::rule DSL#test_0002_loads an empty describe.one block:
NoMethodError: undefined method `instance' for Inspec::InputRegistry:Class
Did you mean?  instance_of?
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:285:in `__apply_waivers'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:54:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `block (2 levels) in create'
    (eval):1:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:159:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:159:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:145:in `load_control_file'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/profile_context_test.rb:17:in `block in <module:DescribeOneTest>'

  2) Error:
Inspec::ProfileContext::its default DSL#test_0002_loads an empty describe.one block:
NoMethodError: undefined method `instance' for Inspec::InputRegistry:Class
Did you mean?  instance_of?
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:285:in `__apply_waivers'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:54:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:137:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:137:in `block (2 levels) in create'
    (eval):1:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:159:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:159:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:145:in `load_control_file'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/profile_context_test.rb:17:in `block in <module:DescribeOneTest>'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
517 % m test/unit/profiles/profile_context_test.rb:18 && minitest test/unit/profiles/profile_context_test.rb
Run options: -n "/^(test_0002_loads\\ an\\ empty\\ describe\\.one\\ block|test_0002_loads\\ an\\ empty\\ describe\\.one\\ block)$/" --seed 44692

# Running:

EE

Finished in 0.150628s, 13.2777 runs/s, 0.0000 assertions/s.

  1) Error:
Inspec::ProfileContext::its default DSL#test_0002_loads an empty describe.one block:
NoMethodError: undefined method `instance' for Inspec::InputRegistry:Class
Did you mean?  instance_of?
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:285:in `__apply_waivers'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:54:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:137:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:137:in `block (2 levels) in create'
    (eval):1:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:159:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:159:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:145:in `load_control_file'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/profile_context_test.rb:17:in `block in <module:DescribeOneTest>'

  2) Error:
Inspec::ProfileContext::rule DSL#test_0002_loads an empty describe.one block:
NoMethodError: undefined method `instance' for Inspec::InputRegistry:Class
Did you mean?  instance_of?
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:285:in `__apply_waivers'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/rule.rb:54:in `initialize'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `new'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/control_eval_context.rb:123:in `block (2 levels) in create'
    (eval):1:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:159:in `instance_eval'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:159:in `load_with_context'
    /Users/ryan/Work/git/inspec/inspec/lib/inspec/profile_context.rb:145:in `load_control_file'
    /Users/ryan/Work/git/inspec/inspec/test/unit/profiles/profile_context_test.rb:17:in `block in <module:DescribeOneTest>'

2 runs, 0 assertions, 0 failures, 2 errors, 0 skips
517 % m test/unit/profiles/profile_context_test.rb:18 && minitest test/unit/profiles/profile_context_test.rb
Run options: -n "/^(test_0002_loads\\ an\\ empty\\ describe\\.one\\ block|test_0002_loads\\ an\\ empty\\ describe\\.one\\ block)$/" --seed 33626

# Running:

..

Finished in 0.217192s, 9.2084 runs/s, 9.2084 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
Run options: --seed 26416

# Running:

.........................................................

Finished in 6.115528s, 9.3205 runs/s, 20.4398 assertions/s.

57 runs, 125 assertions, 0 failures, 0 errors, 0 skips
517 % m test/unit/profiles/profile_context_test.rb:18 && minitest test/unit/profiles/profile_context_test.rb
Run options: -n "/^(test_0002_loads\\ an\\ empty\\ describe\\.one\\ block|test_0002_loads\\ an\\ empty\\ describe\\.one\\ block)$/" --seed 15813

# Running:

..

Finished in 0.213831s, 9.3532 runs/s, 9.3532 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
Run options: --seed 36097

# Running:

.........................................................

Finished in 6.275206s, 9.0834 runs/s, 19.9197 assertions/s.

57 runs, 125 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by zenspider** [comment]
(Also two different failures throughout the run... not sure how relevant that is)

**Comment by clintoncwolfe** [comment]
I have a fix, related to a missing require and a swallowed exception...
EDIT - see #4469
