### ISSUE TITLE
Breaking change in resource filters since 2.0.45

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#2913]
### 🎛 Description

We have profiles that we create and test with inspec 1.x; and now need to test and maintain for both inspec 1.x AND 2.x

### 🌍 InSpec and Platform Version

inspec-2.1.21 via `bundle install`

### 🤔 Replication Case

The following control works in Inspec 1.51 and Inspec 2.0.45 but fails in Inspec 2.1

```
control "Ensure inactive password lock is 30 days or less" do
  title "Ensure inactive password lock is 30 days or less"
  users = shadow.filter(password:/[^!|*]/).params.map { |x| x['user'] }
  unless users.empty?
    users.each do |user|
      describe shadow.users(user) do
        its('inactive_days') { should cmp <= 30 }
      end
    end
  else
    describe 'user password' do
      skip 'no user with password detected'
    end
  end
end
```

### 💁 Possible Solutions

Make the filter method backward compatible

### 💻 Stacktrace

```
root@510dc6aa1821:/workdir# cd /workdir && bundle exec inspec check my_profile
[DEPRECATION] The shadow `users` property is deprecated and will be removed in InSpec 3.0.  Please use `user` instead.
bundler: failed to load command: inspec (/workdir/vendor/bundle/ruby/2.5.0/bin/inspec)
NoMethodError: undefined method `find_all' for nil:NilClass
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/resources/shadow.rb:82:in `block in filter'
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/resources/shadow.rb:79:in `each'
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/resources/shadow.rb:79:in `filter'
  my_profile/controls/my-controls.rb:3:in `block in load_with_context'
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/inspec/rule.rb:50:in `instance_eval'
  /workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.21/lib/inspec/rule.rb:50:in `initialize'
```

**Comment by clintoncwolfe** [comment]
Generally speaking, as v1 to v2 was a major version change, and the project attempts to follow semver, I don't think InSpec generally claims backwards compatibility.  That said, I don't see anything about `shadow` on the [breaking changes list](https://discourse.chef.io/t/inspec-2-0-release/12612).  If we can verify the change was intentional, we can at least document it; if it was unintentional, we can fix it as a bug.

In the meantime, as a (somewhat unpleasant) workaround, you could examine `InSpec::VERSION` and branch accordingly.

**Comment by chris-rock** [comment]
I agree with @clintoncwolfe that semver allows to introduce breaking changes with major versions. We have not done it with InSpec 2. Therefoer all Inspec 1.x baselines minus deprecated features need to work in InSpec 2.0.

In this case it seems that https://github.com/chef/inspec/pull/2642 may broke the shadow resource which was introduced in v2.0.45. @james-stocks can you please verifiy if the control worked with v2.0.32 of InSpec. If it does we have a regression in InSpec that we need to fix since we do not have breaking changes in minor versions.

**Comment by james-stocks** [comment]
@chris-rock `inspec check` succeeds with inspec v2.0.45

```
root@4c41247839c0:/workdir# cd /workdir && bundle exec inspec check src/inspec/rhel7
src/inspec/supported/rhel7/controls/controls.rb:1166: warning: regular expression has ']' without escape
src/rhel7-/controls/controls.rb:1172: warning: regular expression has ']' without escape
[DEPRECATION] The shadow `users` property is deprecated and will be removed in InSpec 3.0.  Please use `user` instead.
Location:    src/inspec/rhel7
Profile:     rhel7
Controls:    189
Timestamp:   2018-04-05T14:50:08+00:00
Valid:       true

  !  src/inspec/rhel7/inspec.yml:0:0: License 'Proprietary, All rights reserved' needs to be in SPDX format. See https://spdx.org/licenses/.
  !  src/inspec/rhel7/controls/controls.rb:655: Control Ensure_password_fields_are_not_empty has no tests defined
  !  src/inspec/rhel7/controls/controls.rb:1036: Control Ensure_permissions_on_all_logfiles_are_configured has no tests defined
...
  !  src/inspec/rhel7/controls/controls.rb:3605: Control Ensure_all_groups_in_etcpasswd_exist_in_etcgroup has no tests defined

Summary:     0 errors, 13 warnings
root@4c41247839c0:/workdir# bundle list inspec
/workdir/vendor/bundle/ruby/2.5.0/gems/inspec-2.0.45
```

**Comment by miah** [comment]
Hi, Thank you for reporting this @james-stocks ! I've been able to replicate this locally, but only when I haven't passed `--sudo` and `--sudo-password` options to InSpec. I think the bug we're hitting lives outside of the shadow resource and I'm working on tracking it down now.

```
$ bundle exec inspec exec shadow-test.rb -t ssh://miah:hunter2@192.168.24.13 --sudo --sudo-password=hunter2
[DEPRECATION] The shadow `users` property is deprecated and will be removed in InSpec 3.0.  Please use `user` instead.
[DEPRECATION] The shadow `users` property is deprecated and will be removed in InSpec 3.0.  Please use `user` instead.
[DEPRECATION] The shadow `users` property is deprecated and will be removed in InSpec 3.0.  Please use `user` instead.
[DEPRECATION] The shadow `users` property is deprecated and will be removed in InSpec 3.0.  Please use `user` instead.

Profile: tests from shadow-test.rb (tests from shadow-test.rb)
Version: (not specified)
Target:  ssh://miah@192.168.24.13:22

  ✔  Shadow file: check shadow file
     ✔  File /etc/shadow mode should cmp == "0000"
     ✔  File /etc/shadow owner should cmp == "root"
     ✔  File /etc/shadow group should cmp == "root"
  ×  Ensure inactive password lock is 30 days or less: Ensure inactive password lock is 30 days or less (2 failed)
     ×  /etc/shadow with user == "root" inactive_days should cmp <= 30

     expected it to be <= 30
          got: ["40"]

     (compared using `cmp` matcher)

     ×  /etc/shadow with user == "miah" inactive_days should cmp <= 30

     expected it to be <= 30
          got: ["40"]

     (compared using `cmp` matcher)

     ✔  /etc/shadow with user == "testuser" inactive_days should cmp <= 30
   ✔  Testuser inactive_days: testuser
     ✔  /etc/shadow with user == "testuser" inactive_days should cmp <= 30


Profile Summary: 2 successful controls, 2 control failures, 0 controls skipped
Test Summary: 5 successful, 3 failures, 0 skipped
```

```
control "Shadow file" do
  title "check shadow file"
  describe file('/etc/shadow') do
    its('mode') { should cmp '0000' }
    its('owner') { should cmp 'root' }
    its('group') { should cmp 'root' }
  end
end

control "Ensure inactive password lock is 30 days or less" do
  title "Ensure inactive password lock is 30 days or less"
  users = shadow.filter(password:/[^!|*|x]/).params.map { |x| x['user'] }
  unless users.empty?
    users.each do |user|
      describe shadow.users(user) do
        its('inactive_days') { should cmp <= 30 }
      end
    end
  else
    describe 'user password' do
      skip 'no user with password detected'
    end
  end
end
control "Testuser inactive_days" do
  title "testuser"
  describe shadow.users('testuser') do
    its('inactive_days') { should cmp <= 30 }
  end
end
```

And when I run without `--sudo`, I get the same error described above. Because the file is un-readable without sudo (on most unixes its mode 0600, and some its 0000). When the file is read, we should be triggering `Inspec::Exceptions::ResourceSkipped` when #read_file_content is called from FileReader. But because thats not happening, our FilterTable ends up empty, and then filter tries to iterate over it. :(

**Comment by davymcaleer** [comment]
Also reported by Novartis Pharmaceuticals in a support ticket - https://getchef.zendesk.com/agent/tickets/18592 - I've referenced this issue back to support for their awareness

**Comment by clintoncwolfe** [comment]
Refs https://github.com/chef/compliance-profiles/issues/270
