### ISSUE TITLE
Dynamic resource loading fails in certain RSpec extension blocks

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4524]
# Describe the problem

The dynamic resource DSL-loading code introduced in #4365 altered the way that the resource DSL is imported into the control code space. User who use RSpec features like `before`/`after` blocks and `shared_example` blocks, which are not documented or supported Chef InSpec features, may experience errors if they reference dynamically loaded resources within such blocks.

First seen publicly in release 4.17.7 of Chef InSpec.

## Reproduction 

```
control "repro-1" do
  describe 'resource-in-before' do
    before(:all) do
      command('true')
    end
    it "required to do something" do
    end
  end
end
```

output:
```
Profile: tests from foo.rb (tests from foo.rb)
Version: (not specified)
Target:  local://

  ×  repro-1: resource-in-before
     ×  resource-in-before required to do something
     undefined method `command' for #<RSpec::ExampleGroups::ResourceInBefore before(:context) hook>

```

**Comment by clintoncwolfe** [comment]
Related - #4521

**Comment by zenspider** [comment]
Tagging @stevendanna so they can track.

**Comment by zenspider** [comment]
Fixed in #4534.

**Comment by stevendanna** [comment]
This doesn't appear to be fixed in 4.18.0 which has the referenced commit.

**Comment by stevendanna** [comment]
```
 > cat repro.rb 
control "repro-1" do
  describe 'resource-in-before' do
    before(:all) do
      command('true')
    end
    it "required to do something" do
    end
  end
end
> hab pkg exec chef/inspec/4.18.0 inspec exec repro.rb 

Profile: tests from repro.rb (tests from repro.rb)
Version: (not specified)
Target:  local://

  ×  repro-1: resource-in-before
     ×  resource-in-before required to do something
     undefined method `command' for #<RSpec::ExampleGroups::ResourceInBefore before(:context) hook>


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
```
