### ISSUE TITLE
Building the www/demo requires some additional commands

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2709]
### Description

I was unable to build the demo that accompanies the site. 

```
cd ~/inspec/www
rake www:demo
ERRORS IN STACKTRACE BELOW
```

There were errors that complained certain types were not available. I was able to get the site to build when I ran the additional commands:

```
cd ~/inspec/www/demo
npm install node-sass
node_modules/.bin/typings install
```

Should these things be added to the README? Is there something that I am missing 

### InSpec and Platform Version

Commit: bd7327b9

### Stacktrace

```
cd ~/inspec/www
rake www:demo
cd demo/ && npm install
npm WARN angular2-quickstart@1.0.0 No repository field.

up to date in 5.283s
cd demo/ && $(npm bin)/gulp build
[23:40:55] Using gulpfile ~/inspec/inspec/www/demo/gulpfile.js
[23:40:55] Starting 'webpack'...
[23:40:55] Starting 'copy'...
[23:40:55] Finished 'copy' after 4 ms
ts-loader: Using typescript@1.8.10 and /Users/franklinwebber/inspec/inspec/www/demo/tsconfig.json
[23:41:01] Version: webpack 1.15.0
                        Asset     Size  Chunks             Chunk Names
    ./dist/inspec_tutorial.js  2.16 MB       0  [emitted]  main
./dist/inspec_tutorial.js.map  3.41 MB       0  [emitted]  main

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser-dynamic/src/facade/lang.d.ts
(11,17): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser-dynamic/src/facade/lang.d.ts
(12,17): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser-dynamic/src/facade/lang.d.ts
(67,59): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser-dynamic/index.d.ts
(98,104): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser-dynamic/index.d.ts
(104,99): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser-dynamic/index.d.ts
(118,113): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts
(18,37): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts
(96,42): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/web_workers/worker/location_providers.d.ts
(21,86): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/web_workers/shared/service_message_broker.d.ts
(35,84): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/web_workers/shared/client_message_broker.d.ts
(32,65): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/web_workers/shared/client_message_broker.d.ts
(40,56): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/lang.d.ts
(11,17): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/lang.d.ts
(12,17): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/lang.d.ts
(67,59): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(1,25): error TS2304: Cannot find name 'MapConstructor'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(2,25): error TS2304: Cannot find name 'SetConstructor'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(4,27): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(4,39): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(7,9): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(8,30): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(11,43): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(12,27): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(14,23): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(15,25): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(100,41): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(101,22): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/platform-browser/src/facade/collection.d.ts
(102,25): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/common/src/directives/ng_class.d.ts
(81,34): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/common/src/facade/lang.d.ts
(11,17): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/common/src/facade/lang.d.ts
(12,17): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/common/src/facade/lang.d.ts
(67,59): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/common/src/pipes/async_pipe.d.ts
(41,38): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/operator/toPromise.d.ts
(7,59): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/operator/toPromise.d.ts
(7,69): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/operator/toPromise.d.ts
(9,9): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/operator/toPromise.d.ts
(10,26): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/operator/toPromise.d.ts
(10,36): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/observable/PromiseObservable.d.ts
(22,31): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/observable/PromiseObservable.d.ts
(23,26): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/http/src/url_search_params.d.ts
(46,16): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/http/src/headers.d.ts
(45,59): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(1,25): error TS2304: Cannot find name 'MapConstructor'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(2,25): error TS2304: Cannot find name 'SetConstructor'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(4,27): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(4,39): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(7,9): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(8,30): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(11,43): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(12,27): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(14,23): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(15,25): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(100,41): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(101,22): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/collection.d.ts
(102,25): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts
(23,53): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts
(36,53): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.d.ts
(11,25): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/ng_module_factory_loader.d.ts
(14,34): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts
(67,148): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts
(108,144): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts
(113,139): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts
(114,135): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/component_resolver.d.ts
(22,58): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/Observable.d.ts
(10,66): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/Observable.d.ts
(66,60): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/rxjs/Observable.d.ts
(66,70): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts
(24,15): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts
(28,16): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/compiler.d.ts
(47,76): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/compiler.d.ts
(62,57): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/linker/compiler.d.ts
(70,73): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/application_init.d.ts
(16,18): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/application_ref.d.ts
(99,88): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/application_ref.d.ts
(134,67): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/application_ref.d.ts
(150,109): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/application_ref.d.ts
(202,67): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/application_ref.d.ts
(204,109): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/application_ref.d.ts
(236,42): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/application_ref.d.ts
(331,33): error TS2304: Cannot find name 'Promise'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/di/reflective_provider.d.ts
(108,123): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/di/reflective_provider.d.ts
(108,165): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/lang.d.ts
(11,17): error TS2304: Cannot find name 'Map'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/lang.d.ts
(12,17): error TS2304: Cannot find name 'Set'.

ERROR in /Users/franklinwebber/inspec/inspec/www/demo/node_modules/@angular/core/src/facade/lang.d.ts
(67,59): error TS2304: Cannot find name 'Map'.
[23:41:02] Finished 'webpack' after 6.89 s
[23:41:02] Starting 'build'...
[23:41:02] Uglify scripts index.html
[23:41:02] Squash css index.html
[23:41:02] Uglify scripts css/inspec_tutorial.css
[23:41:02] Squash css css/inspec_tutorial.css
[23:41:02] Uglify scripts scripts/inspec_tutorial.js
[23:41:04] Squash css scripts/inspec_tutorial.js
[23:41:04] Uglify scripts 3 items
[23:41:04] Squash css 3 items
[23:41:04] Finished 'build' after 2.11 s
....%
```

**Comment by arlimus** [comment]
Fixed and working on current master (2.2.62)
