### PR TITLE
Rollback library eval context de-meta-programming

### LINKED ISSUE #4925: inspec breaks custom resources after 4.18.83
# Describe the problem

The library eval context work on #4814 (included on 4.18.85 and 4.18.95) introduced a regression breaking the inspec-aws resource pack (EDIT: any resource pack that defines custom resources by calling `Inspec.resource(1)` in the `libraries/` folder). 

One workaround is to use version 4.18.51.

## Repro:

A minimal AWS profile (use `inspec init profile -p aws myprofile`) will break:
`inspec exec myprofile -t aws://fakecreds` 

You don't need to actually setup AWS creds to trigger the error.

Stacktrace:
```
NoMethodError: undefined method `resource' for :nope!:Symbol
Did you mean?  rescue
  libraries/aws_backend.rb:154:in `block in initialize'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/dsl_shared.rb:47:in `eval'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/dsl_shared.rb:47:in `require'
  libraries/aws_alb.rb:3:in `load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:170:in `instance_eval'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:170:in `load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:159:in `load_library_file'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:144:in `block in load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:143:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile_context.rb:143:in `load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:272:in `load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:265:in `block in load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:247:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:247:in `each_with_index'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/profile.rb:247:in `load_libraries'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:107:in `block in load'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:101:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:101:in `load'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/runner.rb:129:in `run'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/cli.rb:289:in `exec'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-incident/lib/inspec/base_cli.rb:35:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-incident/inspec-bin/bin/inspec:11:in `<top (required)>'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/inspec:23:in `load'
  /Users/cwolfe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/inspec:23:in `<top (required)>'
```

Related - https://github.com/newcontext-oss/kitchen-terraform/issues/384

### PR DESCRIPTION
**Pull request by clintoncwolfe**
This broke creation of custom resources in resource packs,
and also made private resource registries too private.

Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>

Fixes #4925

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by stevendanna** [comment]
Do we have time to add an integration test that would have caught this?  This feels like a pretty large breakage that we didn't catch.

**Comment by btm** [comment]
@stevendanna I went over this PR live with @clintoncwolfe to prioritize getting this merged and released given that it is a regression. We talked a little about what it would take to add a regression test for this failure. Ultimately, the framework hasn't been written yet but is on the InSpec team's roadmap. Somewhere between this and the Content team which releases the resource packs we'll get that added in the next couple of months. But there isn't an easy solution now relative to our need to get this out.

**Review by btm — APPROVED** [review]
Ignoring code-climate because it lies to me.
