### ISSUE TITLE
inspec 4.18.0 breaks `subject`-style tests

### ISSUE THREAD

**Issue by baurmatt** [inspec/inspec#4587]
# Describe the problem
After upgrading this code breaks:

```
describe service('redis-server') do
  it 'is listening on port 6379' do
    expect(port(6379)).to be_listening
  end
end
```

```
     ×  is listening on port 6379
     undefined method `port' for #<RSpec::ExampleGroups::ServiceRedisServer_2:0x00007fc75d89b350>
```

This works with 4.17.17

## Possible Solution
?

**Comment by clintoncwolfe** [comment]
I'm not sure that code is proper InSpec code to begin with - I've never seen a port property on a service resource (or are you trying to nest resources?).

This works fine in 4.18.0:
```
control "port authority" do
  describe port(443) do
    it { should be_listening }
  end
end
```

**Comment by baurmatt** [comment]
I'm not 100% sure about nested resource, but I think thats what the code was trying to do. I guess the code is missing some service checks and should really look like this:

```ruby
describe service('redis-server') do
  it { should be_running }
  it { should be_enabled }
  it 'is listening on port 6379' do
    expect(port(6379)).to be_listening
  end
end
```

Isn't this proper Inspec code?

**Comment by frezbo** [comment]
as @clintoncwolfe mentioned there is no `port` type for service resource, your code was just calling the `port` resource anyways. It would better to re-write it just using the `port` resource and not inside the `service` resource.

**Comment by frezbo** [comment]
ok I'm reproducing the same issues now:

```
describe 'System python'  do
    it "should exist" do
      expect(file('/bin/python')).to(exist)
    end
    it "should be symlink" do
      expect(file('/bin/python')).to(be_symlink)
    end
    it "should point to Python2" do
      expect(file('/bin/python').link_path).to(eq '/usr/bin/python2.7')
    end
  end
```

Using inspec resources inside `expect` block only works upto 4.16 and is completely broken above that. Ref: #4564 still seems to be partially fixed. FYI: @zenspider 


Another example of failure:

```
describe 'ChefDK' do
    it "version should be 4.13" do
      expect(json('/opt/chefdk/version-manifest.json')['build_version']).to(eq '4.13')
    end
  end
```

**Comment by frezbo** [comment]
@zenspider can you please take a look, this kind of breaks a lot of tests.

**Comment by frezbo** [comment]
@clintoncwolfe This bug seems to have far reaching effects on tests that use Rspec syntax, an example type of tests that are failing

```
control "RHEL-07-020310" do

  describe 'Users with UID 0' do
    subject! { users.where(uid: 0) }
      
    its('usernames') { should eq(%w(root)) }
    its('entries.length') { should eq(1) }
  end
end
```

These tests that define custom `subject` are all breaking. There are a lot of test suites that use this. Upgrading to 4.16 has started breaking almost over 100 tests

**Comment by zenspider** [comment]
This is fixed in #4648 and is a duplicate of #4624. Closing.

**Comment by clintoncwolfe** [comment]
I think you meant a duplicate of #4524.
